name: AutoSignIn
on:
    workflow_dispatch:
    schedule:
    #UTC时间16点对应北京时间0点
    - cron: '50 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v1
        with: 
            python-version: 3.7
      - name: Install
        run: 
            pip install -r requirements.txt
      - name: Run
        env:
            ACCOUNT: ${{secrets.ACCOUNT}}
        run: |
            sudo cp -p chromedriver /usr/bin/
            chmod -R 777 /usr/bin/chromedriver
            python main.py
      # 使用现成的发送邮箱的GitHub action来发送邮件
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
          server_address: smtp.qq.com
          server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 每日健康上报 (${{env.REPORT_DATE}})
         # html_body: file://result.html
          body: 申焘瑀今日健康打卡成功！
          to: ${{secrets.RECEIVE_MAIL}}
          from: 郑州大学数据中台
          convert_markdown: true
          content_type: txt/html